### ISSUE TITLE
midonet-api tries to reuse invalid token after keystone user-role mapping is updated

### ISSUE THREAD

**Issue by hugobenichi** [midokura/python-midonetclient#23]
Follow-up of #627 and #656 in midonet repo. @tomohikokimura correct me if I am wrong:

When a client connect to the api server, the server will get a token from KS on behalf of the client. When that token expires, the api server sends back a 401 to the client with a header indicating the problem. The client catches the error but does not do anything about it, and tries to go back to the api server with the same session cookie. Correct behavior: the client should relog.

logs from quantum server:

013-05-28 14:55:34 ERROR [quantum.api.v2.resource] index failed
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/quantum/api/v2/resource.py", line 82, in resource
result = method(request=request, *_args)
File "/usr/lib/python2.7/dist-packages/quantum/api/v2/base.py", line 239, in index
return self._items(request, True, parent_id)
File "/usr/lib/python2.7/dist-packages/quantum/api/v2/base.py", line 192, in items
obj_list = obj_getter(request.context, *_kwargs)
File "/usr/lib/python2.7/dist-packages/quantum/plugins/midonet/plugin.py", line 482, in get_ports
self.mido_api.get_port(port['id'])
File "/usr/lib/pymodules/python2.7/midonetclient/api.py", line 119, in get_port
return self.app.get_port(id)
File "/usr/lib/pymodules/python2.7/midonetclient/application.py", line 152, in get_port
id_)
File "/usr/lib/pymodules/python2.7/midonetclient/application.py", line 208, in get_port_resource_by_id
headers={'Accept': vendor_media_type.APPLICATION_PORT_JSON})
File "/usr/lib/pymodules/python2.7/midonetclient/auth_lib.py", line 91, in do_request
query=query, headers=headers)
File "/usr/lib/pymodules/python2.7/midonetclient/api_lib.py", line 48, in do_request
response, content = h.request(uri, method, data, headers=headers)
File "/usr/lib/python2.7/dist-packages/httplib2/_init__.py", line 1444, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1205, in request
for authorization in self._auth_from_challenge(host, request_uri, headers, response, content):
File "/usr/lib/python2.7/dist-packages/httplib2/_init__.py", line 1106, in auth_from_challenge
challenges = _parse_www_authenticate(response, 'www-authenticate')
File "/usr/lib/python2.7/dist-packages/httplib2/_init__.py", line 300, in _parse_www_authenticate
raise MalformedHeader("WWW-Authenticate")
MalformedHeader: WWW-Authenticate

at the same time, in midonet-api logs, "token not found" warnings can be found:

14:55:34.374 WARN [] KeystoneClient - KeystoneClient: Token not found

**Comment by tomohikokimura** [comment]
Hugo was correct, and Python Midonet Client just ignored a 401 response received from the API, raising an exception. I've already prepared a patch and sent a pull request.
